name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x

      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        with:
          build: npm run build
          generate: npm run generate
          run: npm run test:e2e:ci
